theme = "monokai_pro_spectrum"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
bufferline = "multiple"
mouse = false
true-color = true
rulers = [80]
trim-trailing-whitespace = true
idle-timeout = 50


[keys.normal]
ret = "insert_mode"
tab = "rotate_view"
F3 = "goto_next_buffer"
F4 = "goto_previous_buffer"
