theme = "monokai_pro_spectrum"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
bufferline = "always"
mouse = false
true-color = true
rulers = [80]
trim-trailing-whitespace = true
