[[language]]
name = "python"
scope = "source.python"
auto-format = true
language-servers = ["pylsp"]
formatter = { command = "black", args = [ "--quiet", "-" ] }

[language-server.jdtls]
command = "jdtls"
args = ["-data", "~/.cache/jdtls/workspace"]

[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ".git"]
language-servers = ["jdtls"]

[language-server.pylsp.config.pylsp.plugins]
pylsp_mypy.enabled = true
pylsp_mypy.live_mode = true
rope_autoimport.enabled = true
